language: php

php:
  - 7.1.11

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan key:generate --force
  - vendor/bin/phpunit --testdox